import type { Metadata } from "next";
import { Manrope, Playfair_Display } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "./components";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menuItems = [
  {
    label: "Home",
    href: "/",
  },
  { label: "Platform Overview", href: "/platform-overview" },
  {
    label: "Why InsurMD",
    href: "/why-insur-md",
  },
  {
    label: "How it Works",
    href: "/how-it-works",
  },
  {
    label: "Integrations & API",
    href: "/integrations-api",
  },
  {
    label: "For Underwriting Teams",
    href: "/underwriting-teams",
  },
  {
    label: "For Reinsurers",
    href: "/reinsurers",
  },
  {
    label: "Use Cases",
    href: "/use-cases",
  },
  {
    label: "Physician Network & Clinical Governance",
    href: "/physician-network-clinical-governance",
  },
  {
    label: "Security & Compliance",
    href: "/security-compliance",
  },
  {
    label: "Applicant Experience",
    href: "/applicant-experience",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${manrope.variable} ${playfair.variable} antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="flex items-center justify-center ">
          <Header menuItems={menuItems} />
        </div>
        {children}
        <Footer menuItems={menuItems} modulesItems={menuItems} />
      </body>
    </html>
  );
}
